# Generated by Django 6.0.3 on 2026-03-10 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=255, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=255, null=True)),
                ('lens', models.CharField(blank=True, max_length=255, null=True)),
                ('focal_length', models.CharField(blank=True, max_length=50, null=True)),
                ('aperture', models.CharField(blank=True, max_length=20, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('blurhash', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_key', models.CharField(max_length=512, unique=True)),
                ('thumbnail_key', models.CharField(max_length=512, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='blog.category')),
            ],
            options={
                'ordering': ['-taken_at', '-created_at'],
                'indexes': [models.Index(fields=['-taken_at'], name='blog_photo_taken_a_664af8_idx'), models.Index(fields=['created_at'], name='blog_photo_created_ebfa88_idx')],
            },
        ),
    ]
