# Generated by Django 6.0.3 on 2026-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
