# Generated by Django 6.0.3 on 2026-03-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_pop_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
