# Generated by Django 6.0.3 on 2026-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
